### ISSUE TITLE
New folder structure

### ISSUE THREAD

**Issue by yosui** [mycel-labs/mycel-docs#49]
[Mycel Document.md](https://github.com/mycel-labs/mycel-docs/files/15358661/Mycel.Document.md)

*   What is Mycel?
    *   Token transfer layer with intent centric architecture
    *   Fragmented Account approach
    *   CAKE: Settlement layer
        *   Settle non-overlay network
            *   Support Anoma
*   What to Build
    *   Intents
    *   Decentralized OTC market
    *   Order Flow Auction
    *   Cross-chain NFT Payment
*   Concept
    *   Transferable Account
        *   [https://www.notion.so/mycel-labs/FA-cb6d3d6204b143349bde351fc1ed28b0](https://www.notion.so/mycel-labs/FA-cb6d3d6204b143349bde351fc1ed28b0)    
    *   Fragmented Account based Order Flow Auction
        *   [https://www.notion.so/mycel-labs/IARMM-Swap-Example-38924ee3935d417d98cfab8d579f24ba](https://www.notion.so/mycel-labs/IARMM-Swap-Example-38924ee3935d417d98cfab8d579f24ba)
*   Tools
    *   Fragmented Account SDK
        *   For Protocols

**Comment by taryune** [comment]
Orderflow auction example
https://www.notion.so/mycel-labs/IARMM-Swap-Example-38924ee3935d417d98cfab8d579f24ba

**Comment by peaceandwhisky** [comment]
I have added a link to the Fragmented Account below Concept.
[https://www.notion.so/mycel-labs/Product-ab79866f2a2340a8aa588ba574ab7617?p=cb6d3d6204b143349bde351fc1ed28b0&pm=s#c314b01e099346218982814550350aac](https://www.notion.so/mycel-labs/Product-ab79866f2a2340a8aa588ba574ab7617?p=cb6d3d6204b143349bde351fc1ed28b0&pm=s#c314b01e099346218982814550350aac)
