### ISSUE TITLE
Add API Spec

### ISSUE THREAD

**Issue by taryune** [mycel-labs/mycel-docs#56]
Add API and authentication spec using SUAVE

**Comment by taryune** [comment]
Auth
https://github.com/mycel-labs/transferable-account/issues/6#issuecomment-2304260012

**Comment by foxytanuki** [comment]
https://github.com/mycel-labs/astraeus/pull/29

**Comment by foxytanuki** [comment]
https://github.com/mycel-labs/mycel-docs/pull/62
